### ISSUE TITLE
Optimization of graph visualization

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#126]
Tracking issue for items related to graph optimization:

- [x] Remove redundant SVG elements (#117).
- [ ] Analyze SVG performance in graph visualization (#125).
- [ ] Switch from SVG to Canvas (#124)

More details in the [research](https://github.com/openrca/orca-ui/issues/4#issuecomment-708234366) discussion.
