### ISSUE TITLE
MVP detailing

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#65]
Tracking issue for items related to MVP detailing:

Layout:

- [x] Organize buttons and filters in the bottom bar (#68).
- [x] Apply dark mode colors to selectors (#68).
- [x] Display graph as main page (#81).

Graph:

- [x] Add object type selector (#66).
- [x] Include cluster and node objects in namespace view (#74).
- [x] Add togglable node labels (#59).
- [x] Fix double icons (#64).
- [x] Decrease graph force (#75).
- [x] Add icon for HPA (#90).
- [x] Fix graph loading for large payload (#91).
- [x] Mark fault trajectories (#107).

Details box:

- [x] Stretch details box to full height (#69).
- [x] Switch object name with object kind in box title (#71).
- [x] Render table from node data (#70).
- [x] Style property table (#92).

Alerts dashboard:

- [x] Reduce alerts table width (#72).
- [x] Use uppercase for severity badges (#72).
- [x] Alert origin should start with a capital case (#72).
- [x] Apply dark mode colors to the table (#72).
- [x] Add alerts count badge (#73).

**Comment by bzurkowski** [comment]
<img width="1440" alt="Screenshot 2020-09-09 at 13 03 41" src="https://user-images.githubusercontent.com/6787563/92590759-08d22b00-f29d-11ea-9ad6-65a5ff72bac3.png">
<img width="1440" alt="Screenshot 2020-09-09 at 13 03 56" src="https://user-images.githubusercontent.com/6787563/92590754-066fd100-f29d-11ea-904b-ce44f62fd0a3.png">
<img width="1440" alt="Screenshot 2020-09-09 at 13 04 04" src="https://user-images.githubusercontent.com/6787563/92590745-0243b380-f29d-11ea-8a10-2a18b70074a3.png">

**Comment by bzurkowski** [comment]
<img width="1440" alt="Screenshot 2020-10-06 at 18 41 09" src="https://user-images.githubusercontent.com/6787563/95231795-e849b200-0803-11eb-816f-e35899adba4c.png">


<img width="1440" alt="Screenshot 2020-10-06 at 18 41 25" src="https://user-images.githubusercontent.com/6787563/95231788-e41d9480-0803-11eb-91ae-52a16a6a2438.png">

**Comment by bzurkowski** [comment]
The MVP is complete! @k-jano @filwie Thanks for your effort 🥇 🥇 🏅
